name: Unit testing windows

on: [push, pull_request]

jobs:

  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: |
        docker pull winamd64/python:3.6
        docker tag winamd64/python:3.6 python:3.6
        docker build . --file tests/Dockerfile --tag test_image
